# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('address3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('is_rental', models.BooleanField(default=False)),
                ('available_date', models.DateTimeField(auto_now=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('kicker', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(choices=[('UN', 'Unit'), ('TW', 'TownHouse'), ('VL', 'Villa'), ('HS', 'House')], default='UN', max_length=2)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('carparking', models.IntegerField()),
                ('built_up_area', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.PropertyType'),
        ),
        migrations.AddField(
            model_name='image',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.Property'),
        ),
    ]
