# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateTimeField(),
        ),
    ]
