# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('property', '0002_auto_20181010_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='profiles.Profile'),
        ),
    ]
