# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20181012_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
