# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20181013_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
